version: '3.8'

networks:
  presto-network:
    driver: bridge

services:
  presto-coordinator:
    container_name: presto-coordinator
    image: prestodb/presto:latest
    ports:
      - 8080:8080
    volumes:
      - ./presto/etc:/opt/presto-server/etc
    environment:
      AWS_ACCESS_KEY: minio
      AWS_SECRET_ACCESS_KEY: minio123
    networks:
      - presto-network

  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    ports:
      - 8181:8181
    volumes:
      - catalog-data:/catalog
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_REGION: us-east-1
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://minio:9090
      CATALOG_URI: jdbc:postgresql://postgres:5432/metastore_db
    networks:
      - presto-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - 5433:5432  # todo change this back to 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: metastore_db
    networks:
      - presto-network

  minio:
    image: minio/minio
    hostname: minio
    container_name: minio
    ports:
      - 9090:9090  # server address
      - 8443:9091  # console address
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DOMAIN: minio
    command: server --address ":9090" --console-address ":9091" /data
    networks:
      presto-network:
        aliases:
          - warehouse.minio

volumes:
  minio-data:
  catalog-data:
  postgres-data:
